[package]
name = "flag"
version = "0.0.0"
edition.workspace = true

[lib]
path = "flag.rs"

[dependencies]
alloc = { workspace = true }
containers = { workspace = true }

[dev-dependencies]
arg = { workspace = true }
