[workspace]
resolver = "2"
members = [
  "bitbuf",
  "charsor",
  "fxhash",
  "genvec",
  "nohash",
  "rangealloc",
  "scopeguard",
  "varint",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
criterion-cycles-per-byte = "0.6.1"
# workspace
bitbuf = { path = "bitbuf" }
charsor = { path = "charsor" }
fxhash = { path = "fxhash" }
genvec = { path = "genvec" }
nohash = { path = "nohash" }
rangealloc = { path = "rangealloc" }
scopeguard = { path = "scopeguard" }
varint = { path = "varint" }

