[workspace]
resolver = "2"
members = [
  "arg",
  "bitbuf",
  "flag",
  "fxhash",
  "genvec",
  "nohash",
  "rangealloc",
  "scopeguard",
  "varint",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
criterion-cycles-per-byte = "0.6.1"
# workspace
arg = { path = "arg" }
bitbuf = { path = "bitbuf" }
flag = { path = "flag" }
fxhash = { path = "fxhash" }
genvec = { path = "genvec" }
nohash = { path = "nohash" }
rangealloc = { path = "rangealloc" }
scopeguard = { path = "scopeguard" }
varint = { path = "varint" }
