[workspace]
resolver = "2"
members = [
  "alloc",
  "arg",
  "bitbuf",
  "flag",
  "fxhash",
  "genvec",
  "nohash",
  "rangealloc",
  "scopeguard",
  "str",
  "varint",
  "vec",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
criterion-cycles-per-byte = { version = "0.6.1" }
allocator-api2 = { version = "0.3.1" }
# workspace
alloc = { path = "alloc" }
arg = { path = "arg" }
bitbuf = { path = "bitbuf" }
flag = { path = "flag" }
fxhash = { path = "fxhash" }
genvec = { path = "genvec" }
nohash = { path = "nohash" }
rangealloc = { path = "rangealloc" }
scopeguard = { path = "scopeguard" }
str = { path = "str" }
varint = { path = "varint" }
vec = { path = "vec" }
