[package]
name = "varint"
version = "0.0.0"
edition.workspace = true

[dev-dependencies]
criterion.workspace = true
criterion-cycles-per-byte.workspace = true

[[bench]]
name = "main"
harness = false
